### ISSUE TITLE
Option to use older tokio(0.2.x) version with new release(0.4.x)

### ISSUE THREAD

**Issue by iamsiddhant05** [rusty-celery/rusty-celery#215]
I was trying to run the below task, but i keep getting an error whenever there is an `await` statement to run?

```rust
#[celery::task]
pub async fn add(x: i32, y: i32) -> TaskResult<i32> {
    println!("{} + {} = {}", x, y, x+y);
    let db_url =
        env::var("DATABASE_URL").unwrap_or("postgres://root@localhost:5432/leads".to_string());
    let pool = PgPool::connect(&db_url).await.unwrap();
     // .. some more code ..//
    Ok(x + y)
}
```

```sh
[2020-12-23T09:54:22Z INFO  celery::app::trace] Task add[c890ad31-3491-4812-a02e-94ec2c049a0b] received
20 + 30 = 50
thread 'tokio-runtime-worker' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /Users/xxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/spawn.rs:131:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is there a way around this or am I doing something wrong here, please let me know?

**Comment by epwalsh** [comment]
Hey @iamsiddhant05, so it sounds like you know what the problem is: a mismatch in tokio versions for different dependencies? And this database library depends on tokio 0.2.*?

Supporting an older version of tokio is probably doable - at least for a single release - but I personally don't have the bandwidth right now as I've got a lot of other tickets on the 0.4.0 milestone that I'd like to get done.

**Comment by iamsiddhant05** [comment]
I guess i'll wait for you guys to move to `tokio 1.0`, almost all my dependencies might align there.
