### ISSUE TITLE
Supports other serializers

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#22]
Currently only JSON supported

**Comment by boylede** [comment]
Hi,

This looked like something I could take a stab at. I added the formats' crates and and modified the MessageBuilder impl to add a fn to set the desired serialization method, as well as updated Message::Body to match on the content-type of the message properties. 

I wasn't sure if I should open a pull request or get some feedback here first. Let me know what you think.

https://github.com/boylede/rusty-celery/commit/a949c54cc5253a048846473b8e7ac04f941e8c5c

Couple things:

* I wasn't sure what tests to add, any input here?

* I added feature flags for each format, but this might not be desired

* I added an additional enum to the error types to encapsulate all the different format errors. Unfortunately the rust messagepack crate uses three separate error types, so there are more entries for that one than otherwise needed.

* I duplicated a chunk of code from Message::body() for each type; I'd prefer to find a more succinct way to format this but the desired functions from each format aren't organized into a trait by serde so I can't use a generic function for it without adding a bunch of boilerplate. A macro would work but that would probably be pretty opaque.

**Comment by epwalsh** [comment]
Hey @boylede, this looks really great! Thanks for taking this.

Please definitely open a PR with what you have. A couple thoughts so far:

- I think we should have tests that serialize and deserialize messages in various formats, checking that the original message is exactly the same as the deserialized one.
- I like the idea of putting these behind feature flags, but having one feature flag for each different format seems a little overkill. Maybe we could put all of the non-default formats (so everything except json) behind a single feature flag.
