### ISSUE TITLE
Question: Rust-Python interop

### ISSUE THREAD

**Issue by Frando** [rusty-celery/rusty-celery#241]
Hi,
I have a question to which I could not find a clear answer in the docs:
Can rusty-celery and Python celery be used together, so that a Python app produces tasks that are executed by a Rust worker with worker functions written in Rust? And the other way round, queue tasks from Rust which are handled by Python workers?
That would be great, but at the same time, with the decoration-based task creation I guess that, if a task is to be queued by Python and handled by Rust, the Python app would need to have something like a stub function for the task function, with the same signature (if that is even possible?) than the actual worker function written in Rust.
Thanks!

**Comment by Frando** [comment]
OK, I tried the examples and it works. Sorry for the noise! Might be good to document how the serialization between Python and Rust is accomplished (i.e. what Rust types to use for which Python types).

**Comment by lowercase00** [comment]
Hi @Frando do you mind sharing what you've learned so far? I'm having a hard time building a Rust app the send tasks to the queue that will be processed by Python, so instead of referencing a function in rust, it would be necessary to enqueue a function name, so that the Python Celery worker can run it. In the examples I could only see how to make things without interaction (Python worker and consumer  / Rust worker and consumer). I was looking for a Rust producer and Python consumer. THanks!

**Comment by rj76** [comment]
I'm also curious about this. Did you manage to get this working, @ccrvlh?

**Comment by ccrvlh** [comment]
No, I ended up using Go and the Celery protocol directly, no libs - I just used it to replace beats, which was a pain to configure and heavy, I can try to get a snippet if you want, this is running on prod for a while now.

**Comment by martinezger** [comment]
> OK, I tried the examples and it works. Sorry for the noise! Might be good to document how the serialization between Python and Rust is accomplished (i.e. what Rust types to use for which Python types).

Could you explain how did you make it work. I have the same problem produce in rust and consume in python.
