### ISSUE TITLE
Should acks_late=false be the default?

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#63]
See https://docs.celeryproject.org/en/latest/userguide/tasks.html and https://docs.celeryproject.org/en/latest/faq.html#faq-acks-late-vs-retry

**Comment by alekhrycaiko** [comment]
Is this still a relevant task/issue? 

Based on the docs you're linking it sounds like this should be default as False, unless it's sensible that tasks are generally idempotent.

**Comment by epwalsh** [comment]
It's still relevant, but is just meant to be a discussion.

Python Celery has `acks_late=false` as the default, but I personally feel that `true` should be the default in Rusty Celery, as this is much safer (provided your tasks are idempotent).

I'd like to hear other opinions though.

**Comment by jcdyer** [comment]
My preference would be to stick with acks_late=false for two reasons: 

1. It's consistent with the way python does it, so less surprising for people converting projects from python.
2. It's an even better default in rust than in python, because error cases are generally marked, either statically by the Result or conventionally by documentation indicating which functions might panic, which makes it even easier to write code that won't crash unexpectedly.

Counter argument to my own point: We're still in the realm of networking, and unrecoverable errors (like pulled network cables, power outages, tornadoes, and wars) can always happen.

**Comment by epwalsh** [comment]
Thanks @jcdyer, those are good points. I think we will leave the default as `false` for the foreseeable future. And I'm actually going to close this issue now as having this open makes it seem like the default is `true` (I think it was initially, but at some point I changed it).
